version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    deploy:
      resources:
        limits:
          memory: 1G
    volumes:
      - sqlserver_data:/var/opt/mssql

  backend:
    build: 
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: sistran_backend
    restart: always
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=SistranDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: sistran_frontend
    environment:
      - VIRTUAL_HOST=sistran.fennereduardo.com
      - LETSENCRYPT_HOST=sistran.fennereduardo.com
      - LETSENCRYPT_EMAIL=admin@fennereduardo.com
    expose:
      - "80"
    depends_on:
      - backend

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=admin@fennereduardo.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  sqlserver_data:
  certs:
  vhost:
  html:
  acme:
