/* ==========================================================================
   Generated Domain Contracts & DTO Schemas
   Feature: User Authentication & Token Issuance
   Architecture: Hexagonal Architecture (Ports & Adapters)
   Stack: typescript + nestjs + prisma
   Generated by gherkin-ai CLI v2.2.0
   ========================================================================== */

import { z } from 'zod';

// --------------------------------------------------------------------------
// 1. Domain Event Interfaces
// --------------------------------------------------------------------------
export interface IDomainEvent {
  eventId: string;
  occurredOn: Date;
  eventType: string;
}



// --------------------------------------------------------------------------
// 2. Command DTO Schemas (Zod Validation)
// --------------------------------------------------------------------------
export const UserAuthenticationTokenIssuanceCommandSchema = z.object({
  requestId: z.string().uuid(),
  timestamp: z.string().datetime(),
  payload: z.object({
    email: z.string(),
    password: z.string(),
    a: z.string(),
    message: z.string()
  })
});

export type UserAuthenticationTokenIssuanceCommand = z.infer<typeof UserAuthenticationTokenIssuanceCommandSchema>;

// --------------------------------------------------------------------------
// 3. Domain Repository Port (Outbound Interface)
// --------------------------------------------------------------------------
export interface IUserAuthenticationTokenIssuanceRepository {
  findById(id: string): Promise<unknown | null>;
  save(entity: unknown): Promise<void>;
  delete(id: string): Promise<void>;
}

// --------------------------------------------------------------------------
// 4. Application Event Publisher Port
// --------------------------------------------------------------------------
export interface IEventPublisher {
  publish(event: IDomainEvent): Promise<void>;
}
