/* ==========================================================================
   Generated Test Fixtures & Seed Setup
   Feature: User Authentication & Token Issuance
   Generated by gherkin-ai CLI
   ========================================================================== */

export interface UserAuthenticationTokenIssuanceFixture {
  id: string;
  email: string;
  password: string;
  a: string;
  message: string;
}

export function createUserAuthenticationTokenIssuanceFixture(): UserAuthenticationTokenIssuanceFixture {
  return {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    email: 'test@example.com',
    password: 'test_value',
    a: 'test_value',
    message: 'test_value',
  };
}

export const GHERKIN_GIVEN_PRECONDITIONS = [
  "a registered user exists with email \"dev@example.com\" and password \"Pass123!\"",
  "a registered user exists with email \"dev@example.com\""
];
